[Desktop Entry]
Name=Tutucustom
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Tutucustom
MetacityTheme=Tutucustom
IconTheme=Faenza-Dark
GtkColorScheme=fg_color:#101010101010,bg_color:#dddddddddddd,text_color:#1a1a1a1a1a1a,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#333333333333,tooltip_fg_color:#000000000000,tooltip_bg_color:#f5f5f5f5b5b5
CursorTheme=Human
CursorSize=18
NotificationTheme=ubuntu
